### ISSUE TITLE
Unpromise support for Thenable objects. aka: Jest makes some promises not a promise

### ISSUE THREAD

**Issue by davidfiala** [cefn/watchable#62]
When using Unpromise with jest I noticed that some node builtins like `Passthrough` and possibly other Readables which expose an async iterator do not return objects that pass `instanceof Promise`. I cannot at this time explain why, but it's a unique phenomena inside of jest. They do seem to be `Thenable` though and work with native `Promise.race`.

Unpromise has an explicit check for `instanceof Promise` which causes these Thenables to be passed to the new Promise constructor which then throws an error.

https://github.com/cefn/watchable/blob/ca7f84e5fbbddd6c79e3fe35d797ace24358f98b/packages/unpromise/src/unpromise.ts#L83

My weak understanding would be that it might be possible for Unpromise to support Thenables more generically than just taking a Promise or testing against instanceof Promise.

Unfortunately, whatever conditions are causing Jest to make a Passthrough async iterator in to "not a promise" does not affect the typescript typing. So the exception occurs at runtime, and can be difficult to track down.

I could and probably should report this with jest, but regardless of outcome it may be advantageous for Unpromise to support Thenables in general since the same memory leaks it aims to fix ought to be present with Thenables as well as promises.

I've attached a minimal PoC that you can use to see the behavior different between running `npm start` vs `npm test`: 
[badjest.zip](https://github.com/cefn/watchable/files/14817460/badjest.zip)

And for keyword SEO, this is the error one might see at runtime if you hit this issue: `TypeError: Promise resolver [object Promise] is not a function`

**Comment by cefn** [comment]
I agree it makes sense to modify the runtime behaviour to try and fit around mainstream patterns.

If it's not a compile-time error and the inverted check is likely to be more robust (e.g. check if `typeof arg === "function"` to differentiate a Promise from an executor instead, so it falls back to being interpreted as a Promise) then we could go ahead with that. 

What do you think?

**Comment by cefn** [comment]
I released as a patch since it was basically a bug. 

Items can confirm to `Promise<T>` structurally without being `instanceof Promise` (tied to the class constructor which was my error). I'm not sure I can extend support for structural interfaces not defined in the Typescript core, though. And for interfaces that ARE defined there, `Promise<T>` has `then()` AND `catch()`. `PromiseLike<T>` has just `then()`.  


* https://github.com/microsoft/TypeScript/blob/98f2c120d8739ae8120b4aa5fc72a0d35a65990d/src/lib/es5.d.ts#L1525
* https://github.com/microsoft/TypeScript/blob/98f2c120d8739ae8120b4aa5fc72a0d35a65990d/src/lib/es2018.promise.d.ts#L4
* https://github.com/microsoft/TypeScript/blob/98f2c120d8739ae8120b4aa5fc72a0d35a65990d/src/lib/es5.d.ts#L1512

For alignment with `Promise` `ProxyPromise` has all the methods - `then()`, `catch()`, `finally()`. 

Not sure how I should handle `catch()` or `finally()` when the backing `PromiseLike` doesn't have any support for them. 

Could be (effectively) a no-op I guess, but I wonder if it's easier to just limit support to things which are duck-typed as a full Promise at least.

**Comment by cefn** [comment]
To be clear about the no-op behaviour, if we went ahead and supported `PromiseLike<T>` we would just need a guard at https://github.com/cefn/watchable/blob/main/packages/unpromise/src/unpromise.ts#L104 to avoid calling catch when it's not present on the underlying object. 

The methods `catch()` and `finally()` would still be inevitably defined on Unpromises (since they are backed by full-blown promises) but `catch()` and the catch-behaviour-of-finally would never be directly triggered by the originating thenable, , because there was never any `catch()` defined in the first place.

**Comment by cefn** [comment]
I just shipped 1.0.0 with static method signatures for resolve() race() and any() that align with the core Promise ones (including for synchronous values). By all means PR some tests (passing or failing) for scenarios you expect to compile at build time or to work at runtime for compatibility with core Promises.

**Comment by cefn** [comment]
Unpromise tests are at https://github.com/cefn/watchable/tree/8e2cf60bfa79321d2060c63905f9e8f7970b1ddd/packages/unpromise/test

**Comment by cefn** [comment]
I had feared that would be the case. The typescript signatures had both array and iterable function overloads, but I convinced myself that it was a matter of fact that `Array<T>` extended `Iterable<T>` so that the array signature may have been a holdover from pre-iterable days. Looks like both overload signatures are still needed.

**Comment by cefn** [comment]
Released [@watchable/unpromise@1.0.1](https://bundlephobia.com/package/@watchable/unpromise@1.0.1) to fix the issue? Is that working better?
